apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-client-server
  labels:
    app: kafka-client-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-client-server
  template:
    metadata:
      labels:
        app: kafka-client-server
    spec:
      containers:
      - name: kafka-client-server
        image: rmsdud2435/kafka-client-server:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8083
        env:
        - name: KAFKA_SERVER_PORT
          valueFrom:
            configMapKeyRef:
              name: kafka-client-server-config
              key: KAFKA_SERVER_PORT
        - name: KAFKA_SERVER_SERVLET_CONTEXT_PATH
          valueFrom:
            configMapKeyRef:
              name: kafka-client-server-config
              key: KAFKA_SERVER_SERVLET_CONTEXT_PATH
        - name: KAFKA_BROKER
          valueFrom:
            configMapKeyRef:
              name: kafka-client-server-config
              key: KAFKA_BROKER
        - name: KAFKA_BROKER_PORT
          valueFrom:
            configMapKeyRef:
              name: kafka-client-server-config
              key: KAFKA_BROKER_PORT
        - name: CONSUMER_GROUP
          valueFrom:
            configMapKeyRef:
              name: kafka-client-server-config
              key: CONSUMER_GROUP
        - name: DB_URL
          valueFrom:
            configMapKeyRef:
              name: kafka-client-server-config
              key: DB_URL
        - name: DB_USERNAME
          valueFrom:
            configMapKeyRef:
              name: kafka-client-server-config
              key: DB_USERNAME
        - name: DB_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: kafka-client-server-config
              key: DB_PASSWORD

